// Generated by CoffeeScript 1.3.3
(function() {

  exports.VSERSION = '1.2';

  exports.TOKEN = 'aS5odW5hbnR2LmNvbQ==';

  exports.domain = 'http://pusher.hunantv.com';

  exports.port = 80;

  exports.numCPUs = require('os').cpus().length;

}).call(this);
