// Generated by CoffeeScript 1.3.3
(function() {
  "use strict";

  var app, configs, express, io;

  express = require('express');

  configs = require('./config');

  app = express.createServer();

  app.listen(configs.port);

  io = require('socket.io').listen(app);

  require('./socket')(io);

  require('./setup')(app, express, io);

  require('./controller')(app, io);

}).call(this);
