exports.VSERSION = '3.0'
# private token
exports.TOKEN = 'aS5odW5hbnR2LmNvbQ=='
exports.domain = 'http://pusher.hunantv.com'
exports.port = 80
exports.socketport = 8870
exports.apiport = 8800
exports.api_runner = 'api.js'
exports.sio_runner = 'sio.js'
exports.numCPUs = require('os').cpus().length
